package_rename_config:
  android:
    app_name: KRW to MYR
    package_name: com.maxchu92.krwtomyr
    override_old_package: com.example.example
    lang: kotlin

  ios:
    app_name: Package Rename Demo
    bundle_name: renamedemo
    override_old_package: com.example.example
    package_name: com.maxchu92.krwtomyr

  web:
    app_name: Package Rename Demo
    description: Package to change project configurations.

  linux:
    app_name: Package Rename Demo
    package_name: com.maxchu92.krwtomyr
    exe_name: renamedemo-linux-x64

  windows:
    app_name: Package Rename Demo
    organization: Maxchu92
    copyright_notice: Copyright ©️ 2025 Maxchu92. All rights reserved.
    exe_name: renamedemo-win32

  macos:
    app_name: Package Rename Demo
    package_name: com.maxchu92.krwtomyr
    copyright_notice: Copyright ©️ 2025 Maxchu92. All rights reserved.
